[exchanges]
# Birdeye API for market data and analytics
birdeye_api_key = "YOUR_BIRDEYE_API_KEY"
birdeye_secret = "YOUR_BIRDEYE_SECRET"

# Binance API for exchange operations
binance_api_key = "YOUR_BINANCE_API_KEY"
binance_secret = "YOUR_BINANCE_SECRET"

[ai_services]
# OpenAI API for GPT-4 predictions
openai_api_key = "YOUR_OPENAI_API_KEY"
openai_org_id = "YOUR_OPENAI_ORG_ID"

[network]
# Helius RPC API
helius_api_key = "YOUR_HELIUS_API_KEY"

# Jito-Solana API
jito_auth_token = "YOUR_JITO_AUTH_TOKEN"

[security]
# Encryption key for sensitive data
encryption_key = "YOUR_ENCRYPTION_KEY"

# Note: All API keys should be encrypted at rest and only decrypted when needed
# Consider using environment variables or a secure key management service in production 